.PHONY: run-spi py run-server

run: run-server

run-server:
	./run.sh

run-spi:
	sudo /home/eugeneai/cardio/src/server/cardio/bin/python3 spi.py

py:
	sudo /home/eugeneai/cardio/src/server/cardio/bin/python3 
